
# This is a reusable workflow for creating an issue

name: Report Results
# Controls when the workflow will run

on:
  workflow_run:
    workflows: ["Pipeline"]
    types: [completed]
    branches: main
        

jobs:
 
  report-result:
    runs-on: ubuntu-latest
    steps:
      - run: echo "reporting"
